<#
.SYNOPSIS
    Extracts InfoPath rules from generated Markdown reports into smaller, focused chunk files.

.DESCRIPTION
    This script reads the "LLM Context.md" and "LLM Context - additional XSL files.md" files 
    generated by the InfoPath-XSN-Analyzer. It parses the main Markdown document and splits 
    the various rule types (Action Rules, Validation, Formatting, etc.) into separate .md files. 
    This creates smaller, more focused context chunks that are easier for LLMs to analyze, 
    avoiding "lost in the middle" context window issues.

.PARAMETER TargetDirectory
    The path to the directory containing the analysis results. You can provide the root project 
    folder (to process all sub-folders) or the path to a specific form's analysis folder.
    Defaults to the current directory (".\").

.EXAMPLE
    .\Extract-RulesForLLM.ps1
    Processes all form analysis folders in the current directory.

.EXAMPLE
    .\Extract-RulesForLLM.ps1 -TargetDirectory .\my-old-infopath-form
    Processes only the specific "my-old-infopath-form" form analysis folder.
#>
param(
    [string]$TargetDirectory = ".\"
)

# Output directory for the LLM chunks
$OutputBaseFolder = "output\LLM_Rules_Extracted"

# Determine if TargetDirectory is a single analysis folder or a parent folder
$analysisDirs = @()
if (Test-Path -Path (Join-Path $TargetDirectory "LLM Context.md")) {
    # It's a single analysis directory
    $analysisDirs += Get-Item $TargetDirectory
} else {
    # Look for subdirectories
    $analysisDirs = Get-ChildItem -Path $TargetDirectory -Directory
}

foreach ($dir in $analysisDirs) {
    $llmContextPath = Join-Path -Path $dir.FullName -ChildPath "LLM Context.md"
    $llmViewsPath = Join-Path -Path $dir.FullName -ChildPath "LLM Context - additional XSL files.md"

    if (Test-Path -Path $llmContextPath) {
        Write-Host "Processing folder: $($dir.FullName)"
        
        # Determine base output path
        # If we passed a specific folder like "dhcr-invoices-original", we still want to put it in a sensible place.
        # Let's put the LLM_Rules_Extracted folder in the parent of the analysis dir, or alongside it.
        $outputDir = Join-Path -Path $dir.Parent.FullName -ChildPath "$OutputBaseFolder\$($dir.Name)"
        if (-not (Test-Path -Path $outputDir)) {
            New-Item -ItemType Directory -Path $outputDir | Out-Null
        }

        # Read the main context file
        $content = Get-Content -Path $llmContextPath -Raw
        
        # Helper function to extract a markdown section by its exact heading
        function Get-MarkdownSection {
            param($text, $heading)
            # Match the heading and everything after it until the next heading of the same or higher level
            $pattern = "(?m)^###\s+$([regex]::Escape($heading))\s*\r?\n([\s\S]*?)(?=^#|\Z)"
            if ($text -match $pattern) {
                return $matches[1].Trim()
            }
            return $null
        }
        
        # Helper function to save and log
        function Save-Chunk {
            param($fileName, $fileContent)
            $filePath = Join-Path $outputDir $fileName
            Set-Content -Path $filePath -Value $fileContent
            Write-Host "  -> Created: $filePath"
        }
        
        # 1-3. Logic (Action, Load, Submit)
        $logicSection = Get-MarkdownSection -text $content -heading "Logic (when / if / then)"
        if ($logicSection) {
            # We will split this table based on the Trigger column
            $lines = $logicSection -split "\r?\n"
            $header = $lines[0..1]
            $body = $lines | Select-Object -Skip 2
            
            $actionRules = @()
            $loadRules = @()
            $submitRules = @()
            
            foreach ($line in $body) {
                if ($line -match "^\|\s*On form load\s*\|") {
                    $loadRules += $line
                } elseif ($line -match "^\|\s*On submit\s*\|") {
                    $submitRules += $line
                } elseif ($line.Trim() -ne "") {
                    $actionRules += $line
                }
            }
            
            if ($actionRules.Count -gt 0) {
                $out = $header + $actionRules | Out-String
                Save-Chunk "01-Action-Rules.md" "### 1. Action Rules`n`n$out"
            }
            if ($loadRules.Count -gt 0) {
                $out = $header + $loadRules | Out-String
                Save-Chunk "02-Form-Load-Rules.md" "### 2. Form Load Rules`n`n$out"
            }
            if ($submitRules.Count -gt 0) {
                $out = $header + $submitRules | Out-String
                Save-Chunk "03-Form-Submit-Rules.md" "### 3. Form Submit Rules`n`n$out"
            }
        }
        
        # 4. Validation Rules
        $validationSection = Get-MarkdownSection -text $content -heading "Validation rules"
        if ($validationSection) {
            Save-Chunk "04-Validation-Rules.md" "### 4. Validation Rules`n`n$validationSection"
        }
        
        # 5. Read-only / disable conditions
        $readOnlySection = Get-MarkdownSection -text $content -heading "Read-only / disable conditions"
        if ($readOnlySection) {
            Save-Chunk "05-Formatting-Rules-ReadOnly.md" "### 5. Formatting Rules (Read-Only / Disable)`n`n$readOnlySection"
        }
        
        # 6. Section visibility
        $visibilitySection = Get-MarkdownSection -text $content -heading "Section visibility"
        if ($visibilitySection) {
            Save-Chunk "06-Formatting-Rules-Visibility.md" "### 6. Formatting Rules (Show / Hide)`n`n$visibilitySection"
        }
        
        # 7. Calculations / dynamic defaults
        $calcSection = Get-MarkdownSection -text $content -heading "Calculations / dynamic defaults"
        if ($calcSection) {
            Save-Chunk "07-Calculations-Dynamic-Defaults.md" "### 7. Calculations (Dynamic Defaults)`n`n$calcSection"
        }
        
        # 8. View navigation
        $navSection = Get-MarkdownSection -text $content -heading "View navigation"
        if ($navSection) {
            Save-Chunk "08-View-Navigation-Rules.md" "### 8. View Switching (Navigation)`n`n$navSection"
        }

        # Additionally, handle the XSL file if it exists, since the user mentioned it
        if (Test-Path -Path $llmViewsPath) {
            $xslOutputPath = Join-Path $outputDir "09-View-Layouts-XSL.md"
            Copy-Item -Path $llmViewsPath -Destination $xslOutputPath -Force
            Write-Host "  -> Copied XSL views to: $xslOutputPath"
        }

        # --- start: compute fields that do NOT have rules and save a chunk ---
        $fieldsSection = Get-MarkdownSection -text $content -heading "Field list"
        
        $fieldCandidates = @()
        if ($fieldsSection) {
            $fieldCandidates = [regex]::Matches($fieldsSection, '(?m)^-\s+(.+)$') | ForEach-Object { $_.Groups[1].Value.Trim() } | Select-Object -Unique
        }

        if ($fieldCandidates.Count -gt 0) {
            $rulesText = ($logicSection, $validationSection, $readOnlySection, $visibilitySection, $calcSection, $navSection) -join "`n"
            if (Test-Path -Path $llmViewsPath) {
                $rulesText += "`n" + [System.IO.File]::ReadAllText($llmViewsPath)
            }
            
            $ruleFields = @()
            foreach ($m in [regex]::Matches($rulesText, '\[(?<f>[^\]]+)\]')) { $ruleFields += $m.Groups['f'].Value }
            foreach ($m in [regex]::Matches($rulesText, 'On change of\s+\[?(?<f>[A-Za-z_][A-Za-z0-9_\-\.]+)\]?','IgnoreCase')) { $ruleFields += $m.Groups['f'].Value }
            foreach ($m in [regex]::Matches($rulesText, 'Set\s+\[?(?<f>[A-Za-z_][A-Za-z0-9_\-\.]+)\]?\s*=','IgnoreCase')) { $ruleFields += $m.Groups['f'].Value }
            foreach ($m in [regex]::Matches($rulesText, '\b([A-Za-z_][A-Za-z0-9_\-\.]{2,})\b')) { $ruleFields += $m.Groups[1].Value }
            
            $ruleFields = $ruleFields | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' } | Select-Object -Unique
            
            $fieldsWithoutRules = @()
            foreach ($f in $fieldCandidates) {
                if (-not ($ruleFields -contains $f)) { $fieldsWithoutRules += $f }
            }
            
            if ($fieldsWithoutRules.Count -gt 0) {
                $body = "### Fields with NO rules detected`n`n"
                $body += ($fieldsWithoutRules | Sort-Object | ForEach-Object { "- $_" }) -join "`n"
                Save-Chunk "00-Fields-No-Rules.md" $body
            } else {
                Save-Chunk "00-Fields-No-Rules.md" "### Fields with NO rules detected`n`n_None found._"
            }
        }
        # --- end: compute fields that do NOT have rules and save a chunk ---
        
        Write-Host "Completed exporting rules for $($dir.Name)."
    }
}
Write-Host "Done!"
